rules = [
  DisableSyntax,
  OrganizeImports
]

DisableSyntax.noVar = false
DisableSyntax.noThrows = false
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true

OrganizeImports {
  targetDialect = Scala3
  removeUnused = false
  groupedImports = Merge
}
